spring:
  application:
    name: trek-rwanda

  datasource:
    url: jdbc:postgresql://localhost:5432/trek_rwanda
    username: postgres
    password: lock-123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  jwt:
    secret: mySecretKeyForJwtTokenGenerationThatIsLongEnoughForHS256Algorithm2026TrekRwanda
    expiration: 86400000
    refresh-expiration: 604800000
